version: '3.7'
services:
  postgres:
    image: postgres:13
    restart: unless-stopped
    environment:
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_DB=${POSTGRES_DB}'
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres:/data/postgres
      - ./latest.dump:/latest.dump
volumes:
  postgres: