version: '3.7'
services:
  postgres:
    image: postgres:13
    restart: unless-stopped
    environment:
      - POSTGRES_USER='${POSTGRES_USER}'
      - POSTGRES_PASSWORD='${POSTGRES_PASSWORD}'
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:${POSTGRES_PORT}'
    volumes:
      - postgres:/data/postgres
volumes:
  postgres: