version: '3.7'
services:
  postgres:
    image: postgres:13
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db
    ports:
      - '5432:5432'
    volumes:
      - postgres:/data/postgres
volumes:
  postgres: